# Uncomment the next line to define a global platform for your project
# platform :ios, '12.2'

target 'Program_6' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Program_6
  pod 'Alamofire', '~> 4.8.1'
  pod 'SwiftyJSON', '~> 4.0'

  target 'Program_6Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Program_6UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
