# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'p6' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for p6
	pod 'Alamofire', '~> 4.7'
	pod 'GoogleAPIClientForREST/Sheets', '~>1.2.1'
	pod 'GoogleSignIn', '~> 4.1.1'

end
